# Generated by Django 4.1.3 on 2022-11-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=50)),
                ('client', models.CharField(max_length=30)),
                ('Priority', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('assigned_to', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
