# Generated by Django 4.1.3 on 2022-11-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='Priority',
            field=models.CharField(max_length=500),
        ),
    ]
