# Generated by Django 4.1.3 on 2022-11-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_issue_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='client',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
